language: go
go:
  - 1.14

sudo: required

os:
  - linux
  - osx

install:
  - echo "install"
  - go get -u github.com/go-bindata/go-bindata/...

script:
  - echo "script"
  - make dev

after_success:
  - bash <(curl -s https://codecov.io/bash)